# Generated by Django 5.1.6 on 2025-03-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carlocation',
            options={'verbose_name': 'Расположение Машины', 'verbose_name_plural': 'Расположение Машин'},
        ),
        migrations.AlterModelOptions(
            name='carreview',
            options={'verbose_name': 'Отзыв Машины', 'verbose_name_plural': 'Отзывы Машин'},
        ),
        migrations.AlterModelOptions(
            name='dealer',
            options={'verbose_name': 'Дилер', 'verbose_name_plural': 'Дилеры'},
        ),
        migrations.AlterModelOptions(
            name='fine',
            options={'verbose_name': 'Штраф', 'verbose_name_plural': 'Штрафы'},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'Аренда', 'verbose_name_plural': 'Аренды'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AlterModelOptions(
            name='triptracking',
            options={'verbose_name': 'Трекер Машины', 'verbose_name_plural': 'Трекер Машин'},
        ),
    ]
