# Generated by Django 5.1.6 on 2025-06-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance'), ('pending_inspection', 'Pending Inspection')], default='available', max_length=20),
        ),
    ]
