# Generated by Django 5.1.6 on 2025-04-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carphoto',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='photos',
            field=models.ManyToManyField(to='rental.carphoto'),
        ),
    ]
