# Generated by Django 5.1.6 on 2025-04-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_remove_carphoto_car_car_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photos',
            field=models.ManyToManyField(blank=True, to='rental.carphoto', verbose_name='Фото'),
        ),
    ]
