# Generated by Django 5.1.6 on 2025-04-05 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_rental_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='is_active',
        ),
    ]
