# Generated by Django 5.1.6 on 2025-03-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_carlocation_options_alter_carreview_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='air_conditioner_available',
            field=models.BooleanField(default=True, verbose_name='Кондиционер'),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default=5, verbose_name='Места'),
        ),
    ]
