# Generated by Django 5.1.6 on 2025-04-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_car_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='main_image',
            field=models.ImageField(upload_to='cars/main/', verbose_name='Главная фотография'),
        ),
    ]
