# Generated by Django 5.1.6 on 2025-03-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_car_air_conditioner_available_car_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='doors',
            field=models.IntegerField(default=4, verbose_name='Двери'),
        ),
    ]
