# Generated by Django 5.1.6 on 2025-03-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_car_doors'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='distance',
            field=models.IntegerField(default=100, verbose_name='Пробег'),
        ),
    ]
