# Generated by Django 5.1.6 on 2025-04-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='email_news',
            field=models.BooleanField(default=False, verbose_name='Новости на email'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='push_notifications',
            field=models.BooleanField(default=False, verbose_name='Push-уведомления'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='sms_alerts',
            field=models.BooleanField(default=False, verbose_name='SMS-уведомления'),
        ),
    ]
